apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ujlo1tpug-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ujlo1tpug-go 
  name: ujlo1tpug-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ujlo1tpug-go 
